name: finapp-ds
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - edgartools>=4.0.0
    - pandas>=1.5.0
    - requests>=2.28.0
    - lxml>=4.9.0
    - html5lib>=1.1
    - tzdata>=2023.3
    - pytz>=2023.3
    - beautifulsoup4>=4.11.0
    - numpy>=1.24.0